document.writeln("  <div class=\'layui-container\' style=\'width: 350px; height: 400px; background: #4D4B4B; ; padding: 0\'>");
document.writeln("");
document.writeln("    <!--上-->");
document.writeln("    <div class=\'layui-row\' style=\'padding: 2%; background: #FFFFFF\'>");
document.writeln("      <div class=\'layui-col-xs6\' style=\'background-color: #FFFFFF;\'>");
document.writeln("        <a style=\'float: left\'>123</a>");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs6\' style=\'background-color: #FFFFFF\'>");
document.writeln("        <p style=\'float: right\'>123</p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <!--中-->");
document.writeln("    <div class=\'layui-row\' style=\'background-color: #FFFFFF; \'>");
document.writeln("      <div class=\'layui-col-xs4\' style=\'text-align: center; padding: 5%;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        123111111");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs4\' style=\' text-align: center; padding: 5%;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        1111111");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs4\' style=\' text-align: center; padding: 5%;\'>");
document.writeln("        123");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("    <!-- 下 -->");
document.writeln("    <div class=\'layui-row\' style=\'padding: 13px\'>");
document.writeln("");
document.writeln("      <div class=\'layui-col-xs4\' style=\'background-color: #92B8B1; text-align: center; padding: 1%;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'layui-row\' style=\'padding: 0\'>");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'layui-row\' style=\'margin-top: 13px\' >");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'layui-row\' style=\'margin-top: 13px\' >");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border-right:0.5px solid #9F9F9F\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("      <div class=\'layui-col-xs3\' style=\'background-color: #92B8B1; text-align: center; margin: 0 13px;");
document.writeln("       border:0.5px solid #FFFFFF; border-radius: 10px\'>");
document.writeln("        尊享");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div style=\'text-align: center; margin-top: 13px\'>");
document.writeln("      123123");
document.writeln("    </div>");
document.writeln("    <div style=\'text-align: center; \'>");
document.writeln("      123123");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("  </div>");
